spring:
  application:
    name: url-shortener-service

  profiles:
    active: dev

#  datasource:
#    url: jdbc:h2:mem:urlshortenerdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener
    username: urlshortener
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false

    show-sql: true

    properties:
      hibernate:
        format_sql: true


server:
  port: 8080

logging:
  level:
    root: INFO
    com.schwab.aiengineering: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics

  endpoint:
    health:
      show-details: always

app:
  base-url: http://localhost:8080

  short-code:
    length: 7

  analytics:
    enabled: true

  expiration:
    default-days: 365

  security:
    allow-custom-alias: true